### ISSUE TITLE
Save way of unique names of the repositories

### ISSUE THREAD

**Issue by AAKempf** [fk-caupo/restic-backup-shell-scripts#7]
A repository name should not be identical on different targets.

Solution:
New variable TARGET

In combination with HOST, unique repository names can be specified.

00-backup.conf:
BACKUP_BOOT_REPOSITORY="${HOST}-${TARGET}-boot"

tools/00-tools.conf:
REPOSITORY="${HOST}-${TARGET}-boot"

It's also time saving because otherwise you have to typing it for every new target once again.

**Comment by fk-caupo** [comment]
This will generate repos more generic.
Should  it be "${HOST}-${TARGET}-boot" or "${TARGET}-${HOST}-boot"?

**Comment by AAKempf** [comment]
From-To-What: 
${HOST}-${TARGET}-boot"

**Comment by fk-caupo** [comment]
Okay. I do agree.

**Comment by fk-caupo** [comment]
We also use BACKUP_TARGET in 00-backup.conf

**Comment by fk-caupo** [comment]
"${HOST}-${TARGET_NAME}-boot"?
in 00-backup.conf
TARGET_ENDPOINT
Endpoint is used in AWS

**Comment by fk-caupo** [comment]
I guess it could be a good idea to have
TARGET
TARGET_NAME
TARGET_ENDPOINT
for further usage

**Comment by fk-caupo** [comment]
Lets keep it simple for the moment.
But keep in mind a construct could be like this;

# local
TARGET="backup-01.caupo.lan"

# remote sftp
TARGET="u123456.your-storagebox.de"


# local
TARGET_NAME="bk-01"

# remote sftp
TARGET_NAME="bx-01"


in 00-backup.conf

# local
# TARGET_ENDPOINT="/mnt/path/host"

# remote sftp
# TARGET_ENDPOINT="sftp:u123456.your-storagebox.de:restic"

# remote s3
# TARGET_ENDPOINT="s3:ams3.digitaloceanspaces.com/bucket/path"
