### ISSUE TITLE
Defining Variables Centrally

### ISSUE THREAD

**Issue by AAKempf** [fk-caupo/restic-backup-shell-scripts#8]
Instead of editing the paths and tags in all files named 2?-backup-*.sh, you can put them in the 00-backup.conf file.

Vars now in each file, f.e.:
```
SOURCE_PATH="/boot"
BACKUP_TAG="boot"
```
Request:
```
BACKUP_BOOT="0"
BACKUP_BOOT_INIT="0"
BACKUP_BOOT_REPOSITORY="repo-ex-01-boot"
BACKUP_BOOT_PATH="/boot"
BACKUP_BOOT_TAG="boot"
```
In each of the files, f.e:
```
SOURCE_PATH=$BACKUP_BOOT_PATH
BACKUP_TAG=$BACKUP_BOOT_TAG
```
Saves time and gives a better overview.

**Comment by fk-caupo** [comment]
Great idea!

**Comment by fk-caupo** [comment]
done
